#' ---
#' title: "01 - Data Understanding and Preparation"
#' output: github_document
#' ---
#'
#' # 1. Data Understanding and Preparation
#'
#' > **Note:** this notebook runs on the **synthetic** dataset generated by
#' > `scripts/00_generate_synthetic_data.R`. The original project used real
#' > telemetry data from a heavy-equipment dealer that cannot be shared; the
#' > synthetic data keeps the same structure and data-quality issues.
#'
#' ## Initial data collection
#'
#' Two sources describe the state of the machines in the hands of customers:
#'
#' * **Telemetry alerts** (`telemetry_alerts.csv`): history of the alerts emitted
#'   by each machine (fault code, machine ID, severity level, product line...).
#' * **Equipment master** (`equipment_master.csv`): descriptive data per machine
#'   (sales date, machine type, last service date...).
#'
#' To narrow the scope, the analysis covers **machines sold between 2011 and 2020
#' with alerts generated during 2020**.
#'
#' ## Libraries

#+ libraries, message=FALSE, warning=FALSE
library(tidyverse)
library(janitor)
library(skimr)
library(lubridate)

#' ## Data description
#'
#' The telemetry alert table contains the following columns:
#'
#' | Column | Description | Type |
#' |---|---|---|
#' | `decal_model_nm` | Machine model | Categorical |
#' | `alert_level` | Alert severity level | Categorical |
#' | `tla_spn_fmi` | Fault code ID | Categorical |
#' | `alert_defn_dsc` | Fault code description | Categorical |
#' | `dealer_name` / `dealer_acct_id` | Dealer name and ID | Categorical |
#' | `pin_prefix` | Origin ID of the machine | Categorical |
#' | `prod_line_nm` | Product line name | Categorical |
#' | `tier_level` | Emission standard | Categorical |
#' | `tla` | Three-letter abbreviation: component group where the fault originates | Categorical |
#' | `first_cptr_tm` | Date the fault code was activated | Date |
#' | `mfg_dt` | Date the machine was activated in telemetry | Date |
#' | `native_pin` / `pin` | Machine ID (full / abbreviated) | Categorical |
#' | `start_of_month` | Month of the fault | Date |
#' | `first_dtc_engn_hours` | Engine hours at the time of the fault | Numeric |
#' | `last_known_engn_hours` | Engine hours at data extraction | Numeric |
#' | `last_known_lat` / `last_known_long` | Last known position | Numeric |
#' | `sum_ocr_cnt` | Number of occurrences of the fault | Numeric |
#'
#' Some variables look important at first glance (`decal_model_nm`,
#' `alert_level`, `first_dtc_engn_hours`, `alert_defn_dsc`, `prod_line_nm`,
#' `sum_ocr_cnt`) but we need to verify that they really are.
#'
#' ## Loading the data

#+ load-data, message=FALSE
base <- read_csv("data/synthetic/telemetry_alerts.csv") %>%
  clean_names()

base_desc <- read_csv("data/synthetic/equipment_master.csv") %>%
  clean_names()

#' The telemetry table has **`r format(nrow(base), big.mark = ",")` rows and
#' `r ncol(base)` columns**; the equipment master has
#' **`r format(nrow(base_desc), big.mark = ",")` machines**.

glimpse(base)

#' ### Machine types
#'
#' The machines are mostly **construction** and **forestry** equipment.
#' The variable `prod_line_nm` gives the product line, and
#' `machine_type_l2` the family it belongs to.

#+ machine-types, fig.width=8, fig.height=4.5
base_desc %>%
  count(machine_type_l3) %>%
  ggplot(aes(x = reorder(machine_type_l3, n), y = n)) +
  geom_col(fill = "#4a6b78") +
  coord_flip() +
  theme_minimal() +
  labs(title = "Machines in the equipment master, by type",
       x = NULL, y = "Number of machines")

#' ### Alert levels
#'
#' We will focus on the variable `alert_level`, which describes the health of
#' the machine. Customers who receive an alert know they must inspect or
#' service the machine. A model able to **predict which machines are prone to
#' more severe failures** would allow the after-sales team to contact those
#' customers *before* the failure happens.
#'
#' * `UNKNOWN`: unknown alerts (sensor triggered by mistake, etc.).
#' * `INFO`: least urgent. The machine is eligible for preventive service.
#' * `YELLOW`: high urgency. The machine can keep working but needs service soon.
#' * `RED`: most urgent. The machine needs immediate attention.

#+ alert-levels, fig.width=7, fig.height=4
base %>%
  count(alert_level) %>%
  mutate(alert_level = factor(alert_level, levels = c("INFO", "YELLOW", "RED", "UNKNOWN"))) %>%
  ggplot(aes(x = alert_level, y = n, fill = alert_level)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c(INFO = "#4f8ec9", YELLOW = "#e0b400",
                               RED = "#c0392b", UNKNOWN = "#7f8c8d")) +
  theme_minimal() +
  labs(title = "Number of alerts by level", x = NULL, y = "Alerts")

#' ## Integration of both sources
#'
#' Both tables are joined by machine ID (`native_pin` = `vin`) to obtain the
#' sales date, machine type and last service date of each machine.

base_join <- left_join(base, base_desc, by = c("native_pin" = "vin"))

dim(base_join)

#' ### Observations before cleaning
#'
#' 1. Dates are stored as `POSIXct`; they need to be converted.
#' 2. Some variables add no value for predicting failures:
#'    * `dealer_name` / `dealer_acct_id`: single dealer, no variability.
#'    * `tier_level`: emission standard.
#'    * `start_of_month`: already contained in the more precise `first_cptr_tm`.
#'    * `last_known_lat` / `last_known_long`: position reported by the machine.
#'    * `pin`: same information as `native_pin`.
#'    * `last_known_engn_hours`: hours at extraction time, not at failure time.
#'
#' We also create two new variables:
#'
#' * `year_sold`: year of the sales invoice.
#' * `prior_service`: `Yes` if the last service was carried out in 2019 or 2020
#'   (i.e. the machine is still in contact with the dealer's service network).

base_join2 <- base_join %>%
  mutate(
    mfg_dt        = as_date(mfg_dt),
    first_cptr_tm = as_date(first_cptr_tm),
    year_sold     = as.character(format(invoice_date, "%Y")),
    service_year  = as.character(format(last_service_date, "%Y")),
    prior_service = factor(case_when(service_year %in% c("2019", "2020") ~ "Yes",
                                     TRUE ~ "No"))
  ) %>%
  select(-dealer_acct_id, -pin, -tier_level, -dealer_name, -start_of_month,
         -last_known_lat, -last_known_long, -last_known_engn_hours,
         -tla_spn_fmi, -service_year, -last_service_date, -invoice_date,
         -brand, -model, -machine_type_l3, -hour_meter, -odometer, -n)

#' After removing the variables above we have **`r ncol(base_join2)` columns**.

skim(base_join2)

#' ## Save intermediate result

dir.create("data/processed", recursive = TRUE, showWarnings = FALSE)
saveRDS(base_join2, "data/processed/base_join2.rds")
